Title = "Minote"

[settings]
  Database = "/home/marc/sync/minote/minote.db"
  recent_notes_limit = 50
  note_width = 500.0
  note_height = 300.0
  initial_view = "pinned"
  initial_layout = "grid"
  grid_max_pages = 50
  font_size = 16.0
  date_format = "02-01-2006"
  time_format = "15:04"
  date_time_format = "[02-01-2006 at 15:04]"
  theme_variant = "dark"
  dark_colour_note = "#2d2d2d"
  light_colour_note = "#e2e2e2"
  dark_colour_bg = "#111111"
  light_colour_bg = "#efefef"
  dark_colour_fg = "#e7e7e7"
  light_colour_fg = "#666666"
  dark_colour_ct_bg = "#1e1e1e"
  light_colour_ct_bg = "#efefef"
  dark_colour_accent = "#d6701c"
  light_colour_accent = "#2684ff"
  dark_colour_button = "#2f2f2f"
  light_colour_button = "#c3c3c3"
