Title = "Minote"

[settings]
  Database = "/home/marc/sync/minote/minote.db"
  recent_notes_limit = 50
  note_width = 500.0
  note_height = 300.0
  initial_view = "pinned"
  initial_layout = "grid"
  grid_max_pages = 50
  theme_variant = "system"
  font_size = 19
  dark_colour_note = "#242424"
  light_colour_note = "#e2e2e2"
  dark_colour_bg = "#111111"
  light_colour_bg = "#efefef"
  dark_colour_ct_bg = "#1e1e1e"
  light_colour_ct_bg = "#efefef"
